export const DISTRICT_STATIONS: Record<string, { name: string; code: string }[]> = {
  "KA_bagalkot": [
    { name: "Badami PS", code: "KA-BAG-BAD91" },
    { name: "Bagalkote Town PS", code: "KA-BAG-BAG26" },
    { name: "Bilgi PS", code: "KA-BAG-BIL79" },
    { name: "Jamakhandi PS", code: "KA-BAG-JAM61" },
  ],
  "KA_ballari": [
    { name: "Ballari Town PS", code: "KA-BAL-BAL52" },
    { name: "Gandhinagar PS (Ballari)", code: "KA-BAL-GAN23" },
    { name: "Hospet Town PS", code: "KA-BAL-HOS67" },
    { name: "Kampli PS", code: "KA-BAL-KAM93" },
    { name: "Sandur PS", code: "KA-BAL-SAN57" },
    { name: "Siruguppa PS", code: "KA-BAL-SIR43" },
  ],
  "KA_belagavi": [
    { name: "Angol PS", code: "KA-BEL-ANG49" },
    { name: "Athani PS", code: "KA-BEL-ATH28" },
    { name: "Camp PS", code: "KA-BEL-CAM83" },
    { name: "Chikkodi PS", code: "KA-BEL-CHI63" },
    { name: "Gokak PS", code: "KA-BEL-GOK87" },
    { name: "Keshwapur PS (Belagavi)", code: "KA-BEL-KES30" },
    { name: "Khade Bazaar PS", code: "KA-BEL-KHA89" },
    { name: "Shahpur PS", code: "KA-BEL-SHA81" },
    { name: "Tilakwadi PS", code: "KA-BEL-TIL77" },
    { name: "Udyambag PS", code: "KA-BEL-UDY67" },
  ],
  "KA_bengaluru_rural": [
    { name: "Anekal PS", code: "KA-BEN-ANE48" },
    { name: "Devanahalli PS", code: "KA-BEN-DEV27" },
    { name: "Doddaballapur Town PS", code: "KA-BEN-DOD22" },
    { name: "Hosakote PS", code: "KA-BEN-HOS28" },
    { name: "Nelamangala PS", code: "KA-BEN-NEL19" },
    { name: "Vijayapura PS (BLR Rural)", code: "KA-BEN-VIJ31" },
  ],
  "KA_bengaluru_urban": [
    { name: "Amruthahalli PS", code: "KA-BEN-AMR70" },
    { name: "BTM Layout PS", code: "KA-BEN-BTM41" },
    { name: "Banashankari PS", code: "KA-BEN-BAN49" },
    { name: "Banaswadi PS", code: "KA-BEN-BAN56" },
    { name: "Basavanagudi PS", code: "KA-BEN-BAS39" },
    { name: "Bellandur PS", code: "KA-BEN-BEL23" },
    { name: "Byatarayanapura PS", code: "KA-BEN-BYA21" },
    { name: "Chamarajpet PS", code: "KA-BEN-CHA63" },
    { name: "Cubbon Park PS", code: "KA-BEN-CUB13" },
    { name: "Electronic City PS", code: "KA-BEN-ELE38" },
    { name: "HAL PS", code: "KA-BEN-HAL75" },
    { name: "HSR Layout PS", code: "KA-BEN-HSR38" },
    { name: "Halasuru PS", code: "KA-BEN-HAL27" },
    { name: "Hebbal PS", code: "KA-BEN-HEB20" },
    { name: "High Grounds PS", code: "KA-BEN-HIG63" },
    { name: "Indiranagar PS", code: "KA-BEN-IND12" },
    { name: "JP Nagar PS", code: "KA-BEN-JP55" },
    { name: "Jayanagar PS", code: "KA-BEN-JAY43" },
    { name: "Jigani PS", code: "KA-BEN-JIG84" },
    { name: "K.R. Puram PS", code: "KA-BEN-KR38" },
    { name: "Kengeri PS", code: "KA-BEN-KEN48" },
    { name: "Konankunte PS", code: "KA-BEN-KON86" },
    { name: "Koramangala PS", code: "KA-BEN-KOR60" },
    { name: "Madivala PS", code: "KA-BEN-MAD27" },
    { name: "Mahadevapura PS", code: "KA-BEN-MAH10" },
    { name: "Malleshwaram PS", code: "KA-BEN-MAL81" },
    { name: "Marathahalli PS", code: "KA-BEN-MAR78" },
    { name: "Peenya PS", code: "KA-BEN-PEE77" },
    { name: "RT Nagar PS", code: "KA-BEN-RT21" },
    { name: "Rajajinagar PS", code: "KA-BEN-RAJ16" },
    { name: "Ramamurthy Nagar PS", code: "KA-BEN-RAM45" },
    { name: "Sadashivanagar PS", code: "KA-BEN-SAD98" },
    { name: "Sanjaynagar PS", code: "KA-BEN-SAN80" },
    { name: "Sarjapur PS", code: "KA-BEN-SAR80" },
    { name: "Seshadripuram PS", code: "KA-BEN-SES59" },
    { name: "Shivajinagar PS", code: "KA-BEN-SHI68" },
    { name: "Ulsoor PS", code: "KA-BEN-ULS65" },
    { name: "Varthur PS", code: "KA-BEN-VAR59" },
    { name: "Vijayanagar PS", code: "KA-BEN-VIJ88" },
    { name: "Whitefield PS", code: "KA-BEN-WHI83" },
    { name: "Wilson Garden PS", code: "KA-BEN-WIL47" },
    { name: "Yelahanka PS", code: "KA-BEN-YEL49" },
    { name: "Yeshwanthpur PS", code: "KA-BEN-YES80" },
  ],
  "KA_bidar": [
    { name: "Aurad PS", code: "KA-BID-AUR88" },
    { name: "Basavakalyan PS", code: "KA-BID-BAS20" },
    { name: "Bhalki PS", code: "KA-BID-BHA51" },
    { name: "Bidar Town PS", code: "KA-BID-BID47" },
  ],
  "KA_chamarajanagar": [
    { name: "Chamarajanagar PS", code: "KA-CHA-CHA91" },
    { name: "Gundlupet PS", code: "KA-CHA-GUN15" },
    { name: "Yelandur PS", code: "KA-CHA-YEL33" },
  ],
  "KA_chikkaballapur": [
    { name: "Chikkaballapur PS", code: "KA-CHI-CHI11" },
    { name: "Chintamani PS", code: "KA-CHI-CHI87" },
    { name: "Gauribidanur PS", code: "KA-CHI-GAU60" },
    { name: "Sidlaghatta PS", code: "KA-CHI-SID19" },
  ],
  "KA_chikkamagaluru": [
    { name: "Chikkamagaluru Town PS", code: "KA-CHI-CHI87" },
    { name: "Kadur PS", code: "KA-CHI-KAD15" },
    { name: "Koppa PS", code: "KA-CHI-KOP24" },
    { name: "Tarikere PS", code: "KA-CHI-TAR68" },
  ],
  "KA_chitradurga": [
    { name: "Challakere PS", code: "KA-CHI-CHA85" },
    { name: "Chitradurga Town PS", code: "KA-CHI-CHI38" },
    { name: "Hiriyur PS", code: "KA-CHI-HIR43" },
    { name: "Holalkere PS", code: "KA-CHI-HOL35" },
    { name: "Hosadurga PS", code: "KA-CHI-HOS32" },
  ],
  "KA_dakshina_kannada": [
    { name: "Bajpe PS", code: "KA-DAK-BAJ82" },
    { name: "Bantwal PS", code: "KA-DAK-BAN95" },
    { name: "Barke PS", code: "KA-DAK-BAR33" },
    { name: "Kavoor PS", code: "KA-DAK-KAV20" },
    { name: "Konaje PS", code: "KA-DAK-KON91" },
    { name: "Mangaluru East PS", code: "KA-DAK-MAN68" },
    { name: "Mangaluru North PS", code: "KA-DAK-MAN92" },
    { name: "Mangaluru South PS", code: "KA-DAK-MAN51" },
    { name: "Panambur PS", code: "KA-DAK-PAN34" },
    { name: "Puttur PS", code: "KA-DAK-PUT16" },
    { name: "Surathkal PS", code: "KA-DAK-SUR95" },
    { name: "Ullal PS", code: "KA-DAK-ULL99" },
  ],
  "KA_davanagere": [
    { name: "Davanagere PS", code: "KA-DAV-DAV26" },
    { name: "Harihar Town PS", code: "KA-DAV-HAR72" },
    { name: "Jagalur PS", code: "KA-DAV-JAG97" },
    { name: "Nittuvalli PS", code: "KA-DAV-NIT22" },
    { name: "Vidyanagar PS (Davanagere)", code: "KA-DAV-VID26" },
  ],
  "KA_dharwad": [
    { name: "Dharwad PS", code: "KA-DHA-DHA90" },
    { name: "Dharwad Suburban PS", code: "KA-DHA-DHA47" },
    { name: "Gokul Road PS", code: "KA-DHA-GOK27" },
    { name: "Hubli Suburban PS", code: "KA-DHA-HUB27" },
    { name: "Keshwapur PS", code: "KA-DHA-KES54" },
    { name: "New Hubli PS", code: "KA-DHA-NEW76" },
    { name: "Old Hubli PS", code: "KA-DHA-OLD90" },
    { name: "Vidyanagar PS", code: "KA-DHA-VID58" },
  ],
  "KA_gadag": [
    { name: "Betageri PS", code: "KA-GAD-BET62" },
    { name: "Gadag Town PS", code: "KA-GAD-GAD71" },
    { name: "Mundargi PS", code: "KA-GAD-MUN37" },
    { name: "Nargund PS", code: "KA-GAD-NAR50" },
  ],
  "KA_hassan": [
    { name: "Arsikere PS", code: "KA-HAS-ARS77" },
    { name: "Belur PS", code: "KA-HAS-BEL20" },
    { name: "Channarayapatna PS", code: "KA-HAS-CHA17" },
    { name: "Hassan Town PS", code: "KA-HAS-HAS32" },
    { name: "Holenarasipura PS", code: "KA-HAS-HOL69" },
    { name: "Sakleshpur PS", code: "KA-HAS-SAK29" },
  ],
  "KA_haveri": [
    { name: "Byadgi PS", code: "KA-HAV-BYA37" },
    { name: "Hanagal PS", code: "KA-HAV-HAN37" },
    { name: "Haveri Town PS", code: "KA-HAV-HAV92" },
    { name: "Ranebennur PS", code: "KA-HAV-RAN28" },
    { name: "Savanur PS", code: "KA-HAV-SAV28" },
  ],
  "KA_kalaburagi": [
    { name: "Aland PS", code: "KA-KAL-ALA32" },
    { name: "Brahmapur PS", code: "KA-KAL-BRA59" },
    { name: "Humnabad PS", code: "KA-KAL-HUM22" },
    { name: "Jewargi Colony PS", code: "KA-KAL-JEW85" },
    { name: "Maha Gandhi Nagar PS", code: "KA-KAL-MAH94" },
    { name: "Sedam PS", code: "KA-KAL-SED11" },
    { name: "Station Bazaar PS", code: "KA-KAL-STA83" },
  ],
  "KA_kodagu": [
    { name: "Kushalnagar PS", code: "KA-KOD-KUS96" },
    { name: "Madikeri Town PS", code: "KA-KOD-MAD26" },
    { name: "Somwarpet PS", code: "KA-KOD-SOM33" },
    { name: "Virajpet PS", code: "KA-KOD-VIR32" },
  ],
  "KA_kolar": [
    { name: "Bangarpet PS", code: "KA-KOL-BAN94" },
    { name: "KGF PS", code: "KA-KOL-KGF26" },
    { name: "Kolar Town PS", code: "KA-KOL-KOL84" },
    { name: "Malur PS", code: "KA-KOL-MAL45" },
    { name: "Mulbagal PS", code: "KA-KOL-MUL93" },
  ],
  "KA_koppal": [
    { name: "Gangavathi PS", code: "KA-KOP-GAN38" },
    { name: "Koppal Town PS", code: "KA-KOP-KOP34" },
    { name: "Kushtagi PS", code: "KA-KOP-KUS39" },
    { name: "Yelburga PS", code: "KA-KOP-YEL32" },
  ],
  "KA_mandya": [
    { name: "Maddur PS", code: "KA-MAN-MAD40" },
    { name: "Malavalli PS", code: "KA-MAN-MAL59" },
    { name: "Mandya Town PS", code: "KA-MAN-MAN72" },
    { name: "Pandavapura PS", code: "KA-MAN-PAN15" },
    { name: "Srirangapatna PS", code: "KA-MAN-SRI91" },
  ],
  "KA_mysuru": [
    { name: "Alanahalli PS", code: "KA-MYS-ALA35" },
    { name: "Devaraja PS", code: "KA-MYS-DEV53" },
    { name: "Hunsur PS", code: "KA-MYS-HUN11" },
    { name: "Jayalakshmipuram PS", code: "KA-MYS-JAY19" },
    { name: "K.R. PS", code: "KA-MYS-KR71" },
    { name: "Lashkar PS", code: "KA-MYS-LAS57" },
    { name: "N.R. PS", code: "KA-MYS-NR46" },
    { name: "Nanjangud Town PS", code: "KA-MYS-NAN36" },
    { name: "Nazarbad PS", code: "KA-MYS-NAZ63" },
    { name: "Saraswathipuram PS", code: "KA-MYS-SAR65" },
    { name: "T. Narasipura PS", code: "KA-MYS-T59" },
    { name: "Udayagiri PS", code: "KA-MYS-UDA22" },
    { name: "V.V. Puram PS", code: "KA-MYS-VV28" },
    { name: "Vijayanagar PS (Mysuru)", code: "KA-MYS-VIJ85" },
  ],
  "KA_raichur": [
    { name: "Devadurga PS", code: "KA-RAI-DEV49" },
    { name: "Lingasugur PS", code: "KA-RAI-LIN51" },
    { name: "Manvi PS", code: "KA-RAI-MAN17" },
    { name: "Raichur Town PS", code: "KA-RAI-RAI74" },
    { name: "Sindhanur PS", code: "KA-RAI-SIN38" },
  ],
  "KA_ramanagara": [
    { name: "Channapatna PS", code: "KA-RAM-CHA21" },
    { name: "Kanakapura PS", code: "KA-RAM-KAN71" },
    { name: "Magadi PS", code: "KA-RAM-MAG48" },
    { name: "Ramanagara PS", code: "KA-RAM-RAM69" },
  ],
  "KA_shivamogga": [
    { name: "Bhadravati Town PS", code: "KA-SHI-BHA79" },
    { name: "Doddapete PS", code: "KA-SHI-DOD10" },
    { name: "Sagar Town PS", code: "KA-SHI-SAG89" },
    { name: "Shikaripura PS", code: "KA-SHI-SHI86" },
    { name: "Shivamogga Town PS", code: "KA-SHI-SHI37" },
  ],
  "KA_tumakuru": [
    { name: "Kunigal PS", code: "KA-TUM-KUN59" },
    { name: "Kyathasandra PS", code: "KA-TUM-KYA54" },
    { name: "Madhugiri PS", code: "KA-TUM-MAD83" },
    { name: "Sira PS", code: "KA-TUM-SIR19" },
    { name: "Tiptur PS", code: "KA-TUM-TIP62" },
    { name: "Tumakuru Town PS", code: "KA-TUM-TUM36" },
  ],
  "KA_udupi": [
    { name: "Brahmavar PS", code: "KA-UDU-BRA72" },
    { name: "Karkala PS", code: "KA-UDU-KAR48" },
    { name: "Kundapur PS", code: "KA-UDU-KUN25" },
    { name: "Malpe PS", code: "KA-UDU-MAL28" },
    { name: "Udupi Town PS", code: "KA-UDU-UDU54" },
  ],
  "KA_uttara_kannada": [
    { name: "Bhatkal PS", code: "KA-UTT-BHA88" },
    { name: "Dandeli PS", code: "KA-UTT-DAN29" },
    { name: "Honnavar PS", code: "KA-UTT-HON67" },
    { name: "Karwar PS", code: "KA-UTT-KAR53" },
    { name: "Kumta PS", code: "KA-UTT-KUM95" },
    { name: "Sirsi PS", code: "KA-UTT-SIR71" },
    { name: "Yellapur PS", code: "KA-UTT-YEL20" },
  ],
  "KA_vijayapura": [
    { name: "Bagewadi PS", code: "KA-VIJ-BAG38" },
    { name: "Indi PS", code: "KA-VIJ-IND26" },
    { name: "Muddebihal PS", code: "KA-VIJ-MUD55" },
    { name: "Sindagi PS", code: "KA-VIJ-SIN68" },
    { name: "Vijayapura Town PS", code: "KA-VIJ-VIJ86" },
  ],
  "KA_yadgir": [
    { name: "Shahapur PS", code: "KA-YAD-SHA41" },
    { name: "Shorapur PS", code: "KA-YAD-SHO74" },
    { name: "Yadgir Town PS", code: "KA-YAD-YAD54" },
  ],
};
